my_blog/accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'accounts'

urlpatterns = [
        path('register/',views.register,name='register'),
        path('my_questions/',views.my_questions,name='my_questions'),
        path('favourite_articles/',views.favourite_articles,name='favourite_articles'),
        path('favourite_books/',views.favourite_books,name='favourite_books'),
]

my_blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.list,name='list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name = 'post_detail'),
    path('category/<slug:slug>/',views.post_category,name = 'category_list'),
    path('like/',views.post_like,name='like'),
]

my_blog/books_app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'books_app'

urlpatterns = [
    path('', views.list_book,name='list_book'),
    path('<slug:slug>',views.book_detail,name='book_detail'),
    path('download/<slug:slug>/',views.download_book,name='download_book'),
    path('category-book/<slug:slug>/',views.category_book,name = 'category_book'),
    
    path('books/like/',views.books_like,name='like'),

]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap
from services.sitemaps import ServiceSiteMap 
from questions.sitemaps import QuestionsSiteMap
from books_app.sitemaps import BooksSiteMap

sitemaps = {
        'posts':ArticleSitemap,
        'services':ServiceSiteMap,
        'questions':QuestionsSiteMap,
        'books':BooksSiteMap,
        }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}),
    path('services/',include('services.urls',namespace = 'service')),
    path('questions/',include('questions.urls',namespace='questions')),
    path('books/',include('books_app.urls',namespace='books_app')),
    path('auth/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('social-auth/',include('social_django.urls',namespace='social'))

    
    
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/questions/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'questions'

urlpatterns = [
    path('',views.show_questions,name='all_questions'),
    path('<slug:slug>',views.questions_detail, name='question_details'),
    path('tag/<slug:slug>',views.show_tag_questions,name ='tag_questions'),
    path('create_questions/',views.create_questions,name='create_questions'),
]

my_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.contrib.sitemaps import Sitemap
from django.conf import settings

class Category(models.Model):
    title = models.CharField(max_length=50,verbose_name='Категория')
    slug = models.SlugField(blank = True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    def get_absolute_url(self):
        return reverse('blog:category_list', args = [self.slug])



class Article(models.Model):
    STATUS_CHOICE = (
            ('draft',"Draft"),
            ('publish',"Publish")
            )
    author = models.ForeignKey(User,on_delete = models.CASCADE,related_name = 'blog_posts')
    meta_description = models.CharField(max_length=250,verbose_name='Мета описание')
    meta_keyword = models.CharField(max_length = 250,verbose_name='Ключевые слова (ключ 1, ключ 2, ключ 3…)')
    category = models.ForeignKey(Category,on_delete = models.CASCADE)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length = 250,unique = True)
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    create = models.DateTimeField(auto_now_add = True)
    update = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 10,choices = STATUS_CHOICE,default = 'draft')
    image = models.ImageField()
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='articles_like',blank=True)

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',  args = [self.publish.year,self.publish.month,self.publish.day,self.slug])

class Comment(models.Model):
    name = models.CharField(max_length = 50)
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add = True)
    body = models.TextField()
    post = models.ForeignKey(Article,on_delete = models.CASCADE,related_name = 'comments')
    active = models.BooleanField(default = True)

    class Meta:
        ordering = ('-date',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.name

class BlogSiteMap(Sitemap):
    changefreq = 'never'
    priopiry = 0.5

    def items(self):
        return Article.objects.all()

my_blog/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from .models import Article,Category
from .forms import CommentForm
from django.db.models import Q
from services.models import ServiceModel
from services.models import ServicePost
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required



def list(request):
    #services = ServiceModel.objects.all()
    search_query = request.GET.get('search','')
    if search_query:
        articles = Article.objects.filter(Q(title__icontains = search_query)| Q(body__icontains = search_query))
    else:
        articles = Article.objects.all().filter(status='publish')
    categories = Category.objects.all()
    paginator = Paginator(articles,1)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    draft_posts = Article.objects.all().filter(status='draft')


    return render(request,'blog/index.html',{"posts":posts,'page':page,'categories':categories,'draft_posts':draft_posts})




def post_detail(request,year,month,day,post):
    
    categoryes = Category.objects.all()
    post = get_object_or_404(Article,slug = post,status = 'publish',publish__year = year,publish__month = month,publish__day=day) 
    comments = post.comments.filter(active = True)

    if request.method == "POST":
        form  = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit = False)
            new_comment.post = post
            new_comment.save()



            

    form = CommentForm()
    return render(request,'blog/detail.html',{'post':post,'comments':comments,'form':form,'categories':categoryes})

def post_category(request,slug):

    category = Category.objects.get(slug = slug)
    search_query = request.GET.get('search','')
    if search_query:
        posts= Article.objects.filter(Q(title__icontains = search_query)| Q(body__icontains = search_query))
    else:
        posts= Article.objects.filter(category = category)


    services = ServiceModel.objects.all()
    categories = Category.objects.all()
    paginator = Paginator(posts, 1)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/category.html', {
        'category': category,
        'page': page,
        'posts': posts,
        'categories':categories,
        'services':services})

@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Article.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ok'})

my_blog/blog/templates/blog/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block meta_description%}{% endblock%}">
    <meta name="keywords" content="{% block meta_keyword%} {% endblock %}" />
    <meta name="robots" content="{%block robots%}all{% endblock%}" />
 


	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
	<link href="https://fonts.googleapis.com/css2?family=Cuprum&display=swap" rel="stylesheet">
    
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.0/jquery.matchHeight-min.js"></script>
<link href="https://fonts.googleapis.com/css2?family=Sora:wght@200&display=swap" rel="stylesheet">
<title>{% block title %} {% endblock%}</title>
</head>
<body>
<header class='mb-4'>
	<div class="container p-0">
		<div class="header-title">
            <h5 class='ml-3'>Блог начинающего <span class='text-primary' style='color:#00b4ef;'>программиста</span></h5>
		</div>
		<nav >
  <ul class="top-menu">
      <li><a href="{% url 'blog:list'%}">Главная</a></li>
    <li class="dropdown-standart"><a class='disabled' href="" class="dropdown">Сервисы</a>
      <ul class="submenu-standart">
{% for s in services%}

<li><a href="{{s.get_absolute_url}}">{{s.title}}</a></li>


{% endfor %}
        
      </ul>
    </li>
    <li><a href="{% url 'questions:all_questions'%}">Вопрос ответ</a></li>
    <li><a href="{% url 'books_app:list_book'%}">Книги</a></li>
    {% if request.user.is_authenticated%}
    <li style='float:right;' class="dropdown-standart"><a class='disabled' href="" class="dropdown">{{user.username}}</a>
      <ul class="submenu-standart">

        

          <li><a href="{% url 'accounts:my_questions'%}">Мои вопросы {% with user_question.count as questions%} ({{questions}}){% endwith%} </a></li>

          <li><a href="{% url 'accounts:favourite_articles'%}">Понравившиеся статьи</a></li>
          
          <li><a href="{% url 'accounts:favourite_books'%}">Понравившиеся книги</a></li>

    <li><a href="{% url 'logout'%}">Выйти</a></li>    
      </ul>
    </li>


    {% else%}
    <li style='float:right'><a href="{% url 'accounts:register'%}">Зарегестрироваться</a></li>
    <li style='float:right'><a href="{% url 'login'%}">Войти</a></li>
    {% endif%}
   
  </ul>
</nav>
	</div>
</header>

<main>
	
	<div class="container">
        {% block content %}


        {% endblock%}
		
			</div>



	
</main>

</body>
{% block script%} {%endblock%}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src='{% static 'jquery-3.5.1.min.js'%}'></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
var csrftoken = Cookies.get('csrftoken');
function csrfSafeMethod(method){
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr,settings){
        if(!csrfSafeMethod(settings.type) && !this.crossDomain){
            xhr.setRequestHeader("X-CSRFToken",csrftoken);
        }
    }
})
$(document).ready(function(){
{% block domready %}{% endblock %}
});
</script>
</html>

my_blog/blog/templates/blog/category.html
{% extends 'blog/base.html'%}
{% block title%}Категория {{category}}{% endblock%}

{% block meta_description%} Самые новые и интересные статьи этого блога {% endblock%}


{% block meta_keyword%}html, css, javascript, python, php, ajax, django, веб сервисы{% endblock %}

{% block content %}
<div class="row">
			<div class="col-lg-8 main-content">
                <div class='container-fluid'>
                
                <ul>
                    {% if posts %}
                    {% for post in posts%}
                <li class='main-item mb-3'>
						<div class="card mb-3">
                         <div class="row">
                           <div class="col-md-4">
                               <img src="{{post.image.url}}" style='height: 100%' class="card-img" alt="...">
                           </div>
                           <div class="col-md-8">
                             <div class="card-body">
                                 <a href="{{post.get_absolute_url}}" class='text-dark item-url'><h5 class="card-title mb-0">{{post.title}}</h5></a>
                                 <p class="card-text">{{post.body|truncatechars:60}}</p>
                               <div class="row">
                               	<div class="col-lg-6">
                                    <button type="button" class="btn btn-primary"><a href="{{post.get_absolute_url}}" style='text-decoration: none;color:#fff;'>Читать</a></button>
                               	</div>
                               	<div class="col-lg-6">
                                    <p class="card-text"><small class="text-muted">Создано {{post.create}}</small></p>
                               	</div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
					</li>

                    {%endfor%}
                </ul>
                
                
        {% include 'blog/pagination.html' with page=posts%}
                {% else %}
                <h3 class='ml-3'> Постов еще нет</h3>

                {% endif %}


                
                
                
                
                </div>	
			</div>


			<div class="col-lg-4   mb-3 main-sidebar">
<div class='container'>
                    
                    <nav class="navbar text-center p-0 mb-3">
                    <form class="form-inline" action='{% url 'blog:list'%}'>
                        <div class='row'>
 <div class='col-sm-8 col-8'>
                        
                        
                  <input class="form-control  w-100" type="search" placeholder="Поиск" aria-label="Поиск" name='search'>
                        
                        </div>  

                        <div class='col-sm-4 col-4'>
                        
                        
                        
                  <button class="btn btn-outline-primary ml-2" type="submit">Поиск</button>
                        </div>
            
            
            
            
            
            </div> 
                </form>
              </nav>

                    
                    
                    </div>



								<div class="list-group sticky-top mt-3">

					<h1 class = 'sidebar-category'>Категории</h1>
                    {% for category in categories %}

                    <a href="{{category.get_absolute_url}}" class="list-group-item list-group-item-action">{{category.title}}</a>
                    {% endfor %}
                </div>
			</div>
		</div>

    
        {% endblock%}
{% block script %}
<script type='text/javascript'>
    function ajaxPagination(){
        $('ul.pagination a.page-link').each((index,el)=>{
            $(el).click((e)=>{
                e.preventDefault()
                let page_url = $(el).attr('href')

                var dfd = $.ajax({
                    url:page_url,
                    type:"GET",
                    async:true,
                    success:(data)=>{
                        $('.main-content').empty()
                    
                        $('.main-content').append($(data).find('.main-content').html())
                        ajaxPagination()
                    }
                })
            })
        })
    }


$(document).ready(function(){
    ajaxPagination()
})

</script>
{% endblock%}

my_blog/blog/templates/blog/detail.html
{% extends 'blog/base.html'%}	
{% block title%}{{post.title}} {% endblock%}

{% block meta_description%} {{post.meta_description}}{% endblock%}

{% block meta_keyword%}{{post.meta_keyword}} {% endblock %}


{% block content %}
		<div class="row">
            <div class="col-lg-8 main-content detail_content">

            <div class='container-fluid'>
				<div class="card  mb-3">
                    <img class="card-img-top" src="{{post.image.url}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{post.title}}</h5>
                <p class="card-text mb-0"><small class="text-muted">Автор {{post.author}}: Создано {{post.create}}</small></p>
                <p class ='card-text mb-3'><small class='text-muted'>Категория: {{post.category}} </small></p>
                {{post.body|safe}}
            </div>
            {% with total_likes=post.users_like.count users_like=post.users_like.all %}
            <div class="card-body">
<div>
<span class="count" style='font-size:16px;'>
<span style='font-size:16px;' class="total text-uppercase ml-3 mt-2">{{ total_likes }}  </span>
like{{total_likes|pluralize}}
</span>
<a href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"  class="like button btn btn-{% if request.user in users_like %}outline-{% endif %}success ml-2">
{% if request.user not in users_like %}
Like
{% else %}
Unlike
{% endif %}
</a>
</div>
</div>
            


            {% endwith %}
          </div>
         {% with comments.count as total_comments %}
          <p class ='ml-3' style='font-size: 19px;'>Комментариев ({{total_comments}})</p>
          {% endwith %}
          {% for comment in comments %}
          
          <div class="card  mb-3">
  
            <div class="card-body">
                <h5 class="card-title">{{comment.name}}</h5>
                <p class="card-text">{{comment.body}}</p>
                <p class="card-text"><small class="text-muted">{{comment.date}}</small></p>
    
            </div>
          </div> 


          {% endfor %}

    {% if request.user.is_authenticated%}
          <form class='' action = '' method = 'post'>
              {% csrf_token %}
            <p class='ml-3' style='font-size: 19px;'>Добавить комментарий</p>
  <div class="row mb-2">
    <div class="col">
        {{form.name}}
    </div>
    <div class="col">
        {{form.email}}
    </div>
  </div>
  {{form.body}}
  <input type='submit' class='ml-3 btn btn-primary mb-4' value= 'Отправить'>
  
</form>
{% else%}

          <p class ='ml-3 mt-3 mb-3' style='font-size: 19px;'>Чтобы оставить комментарий авторизуйтесь</p>
          {% endif%}
           
            </div>	
			</div>
			<div class="col-lg-4 main-sidebar">
				<div class="list-group sticky-top mt-3">
					<h1 class = 'sidebar-category pl-3'>Категории</h1>
                    {% for category in categories %}

                    <a href="{{category.get_absolute_url}}" class="list-group-item list-group-item-action">{{category.title}}</a>
                    {% endfor %}

</div>
			</div>
		</div>


		
		
	</div>



    {% endblock%}	



    {% block domready %}

    $('a.like').click(function(e){
        e.preventDefault();
        $.post(
        '{% url 'blog:like'%}',
        {id:$(this).data('id'),action:$(this).data('action')},
        function(data){
        if(data['status']=='ok'){
        var previous_action = $('a.like').data('action');
        $('a.like').data('action',previous_action =='like' ? 'unlike':'like');
        $('a.like').text(previous_action =='like' ? 'Unlike':'Like');
        var previous_likes = parseInt($('span.count .total').text());
        $('span.count .total').text(

        previous_action == 'like'?previous_likes+1:previous_likes-1);
        }
        }
        )


    })





{% endblock %}

my_blog/blog/templates/blog/index.html
{% extends 'blog/base.html'%}
{% block title%}Главная {% endblock%}
{% block meta_description%} Самые новые и интересные статьи этого блога {% endblock%}

{% block meta_keyword%}html, css, javascript, python, php, ajax, django, веб сервисы{% endblock %}



{% block content %}
<div class="row">
			<div class="col-lg-8 main-content">
                <div class='container-fluid'>
                
                <ul>
                {% if user.is_authenticated%}
                    {% if posts %}
                    {% for post in draft_posts%}
                <li class='main-item mb-3'>
						<div class="card mb-3">
                         <div class="row">
                           <div class="col-md-4">
                               <img src="{{post.image.url}}" style='height: 100%' class="card-img" alt="...">
                           </div>
                           <div class="col-md-8">
                             <div class="card-body">
                                 <a href="{{post.get_absolute_url}}" class='text-dark item-url'><h5 class="card-title mb-0">{{post.title}}</h5></a>
                                 <p class="card-text">{{post.body|truncatechars:60}}</p>
                               <div class="row">
                               	<div class="col-lg-6">
                                    
                                    <a class='btn btn-primary' href="{{post.get_absolute_url}}" style='text-decoration: none;color:#fff;'>Читать</a>
                               	</div>
                               	<div class="col-lg-6">
                                    <p class="card-text"><small class="text-muted">Создано {{post.publish}}</small></p>
                               	</div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
					</li>

                    {%endfor%}



                {% endif%}
                {% endif%}


                    {% if posts %}
                    {% for post in posts%}
                <li class='main-item mb-3'>
						<div class="card mb-3">
                         <div class="row">
                           <div class="col-md-4">
                               <img src="{{post.image.url}}" style='height: 100%' class="card-img" alt="...">
                           </div>
                           <div class="col-md-8">
                             <div class="card-body">
                                 <a href="{{post.get_absolute_url}}" class='text-dark item-url'><h5 class="card-title mb-0">{{post.title}}</h5></a>
                                 <p class="card-text">{{post.body|truncatechars:60}}</p>
                               <div class="row">
                               	<div class="col-lg-6">
                                    
                                    <a class='btn btn-primary' href="{{post.get_absolute_url}}" style='text-decoration: none;color:#fff;'>Читать</a>
                               	</div>
                               	<div class="col-lg-6">
                                    <p class="card-text"><small class="text-muted">Создано {{post.publish}}</small></p>
                               	</div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
					</li>

                    {%endfor%}
                </ul>

        {% include 'blog/pagination.html' with page=posts%}
                {% else%} 
                <h3 class='card-text'>Постов еще нет</h3>
{% endif %}



            			</div>

                
                
                </div>	

			<div class="col-lg-4 mb-3 main-sidebar">


                    <div class='container-fluid'>
                    
                    <nav class="navbar text-center p-0 mb-3">
                    <form class="form-inline" action='{% url 'blog:list'%}'>
                        <div class='row'>
                     <div class='col-sm-8 col-8'>
                        
                        
                  <input class="form-control w-100" type="search" placeholder="Поиск" aria-label="Поиск" name='search'>
                        
                        </div>  

                        <div class='col-sm-4 col-4'>
                        
                        
                        
                  <button class="btn btn-outline-primary ml-1" type="submit">Поиск</button>
                        </div>
            
            
            
            
            
            </div> 
                </form>
              </nav>

                    
                    
                    </div>








								<div class="list-group sticky-top mt-3">

					<h1 class = 'sidebar-category pl-3'>Категории</h1>
                    {% for category in categories %}

                    <a href="{{category.get_absolute_url}}" class="list-group-item list-group-item-action">{{category.title}}</a>
                    {% endfor %}
                </div>
			</div>
		</div>

    
        {% endblock%}



{% block script %}
<script type='text/javascript'>
    function ajaxPagination(){
        $('ul.pagination a.page-link').each((index,el)=>{
            $(el).click((e)=>{
                e.preventDefault()
                let page_url = $(el).attr('href')

                var dfd = $.ajax({
                    url:page_url,
                    type:"GET",
                    async:true,
                    success:(data)=>{
                        $('.main-content').empty()
                    
                        $('.main-content').append($(data).find('.main-content').html())
                        ajaxPagination()
                    }
                })
            })
        })
    }


$(document).ready(function(){
    ajaxPagination()
})

</script>
{% endblock%}

my_blog/blog/templates/blog/pagination.html
<div class="pagination ml-3 mb-3">
			<nav aria-label="Page navigation example mb-3">
              <ul class="pagination">
              <li class="page-item">
                  {% if page.has_previous%}
                  <a class="page-link" href='?page={{page.previous_page_number}}' aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a>

                  {% endif%}
              </li>
              {%for p in page.paginator.page_range %}
              <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                    {% endfor%}

                {% if page.has_next%}
                <li class='page-item'>
                    <a class="page-link" href="?page={{page.next_page_number}}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
                {% endif%}
                
              </ul>
            </nav>
		</div>
		