my_blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.list,name='list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name = 'post_detail'),
    path('category/<slug:slug>/',views.post_category,name = 'category_list'),
    path('like/',views.post_like,name='like'),
]

my_blog/books_app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'books_app'

urlpatterns = [
    path('', views.list_book,name='list_book'),
    path('<slug:slug>',views.book_detail,name='book_detail'),
    path('download/<slug:slug>/',views.download_book,name='download_book'),
    path('category-book/<slug:slug>/',views.category_book,name = 'category_book'),
    
    path('books/like/',views.books_like,name='like'),

]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap
from services.sitemaps import ServiceSiteMap 
from questions.sitemaps import QuestionsSiteMap
from books_app.sitemaps import BooksSiteMap

sitemaps = {
        'posts':ArticleSitemap,
        'services':ServiceSiteMap,
        'questions':QuestionsSiteMap,
        'books':BooksSiteMap,
        }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}),
    path('services/',include('services.urls',namespace = 'service')),
    path('questions/',include('questions.urls',namespace='questions')),
    path('books/',include('books_app.urls',namespace='books_app')),
    path('auth/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('social-auth/',include('social_django.urls',namespace='social'))

    
    
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/books_app/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=50,verbose_name='Категория')
    slug = models.SlugField(blank = True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    def get_absolute_url(self):
        return reverse('books_app:category_book', args = [self.slug])



class Books(models.Model):
    title = models.CharField(max_length = 255)
    description = models.TextField()
    slug = models.SlugField()
    books_file = models.FileField(upload_to = 'books/')
    books_image = models.ImageField(upload_to = 'books/image/')
    publish = models.DateTimeField(auto_now_add = True)
    category = models.ForeignKey(Category,on_delete = models.CASCADE)
    meta_description = models.CharField(max_length = 255,verbose_name='Мета дескриптион')
    meta_keywords = models.CharField(max_length = 255,verbose_name='Meta Keywords')

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='books_like',blank=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Книгa'
        verbose_name_plural = 'Книги'

    def get_absolute_url(self):

        return reverse('books_app:book_detail', args = [self.slug])


class Comment(models.Model):
    name = models.CharField(max_length = 50)
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add = True)
    body = models.TextField()
    book= models.ForeignKey(Books,on_delete = models.CASCADE,related_name = 'comments')
    active = models.BooleanField(default = True)

    class Meta:
        ordering = ('-date',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.name

my_blog/books_app/forms.py
from django.forms import ModelForm,TextInput,EmailInput,Textarea
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','body']
        widgets = {'name':TextInput(attrs = {'class':'form-control','placeholder':'Имя'}),
                'email':EmailInput(attrs = {'class':'form-control','placeholder':'Email'}),
                'body':Textarea(attrs = {'class':'form-control mb-2','id':'exampleFormControlTextarea1','rows':'3','placeholder':'Текст комментария'})}

my_blog/books_app/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Books,Category
from services.models import ServiceModel
from .forms import CommentForm
from django.shortcuts import redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required


# Create your views here.


def list_book(request):
    search_query = request.GET.get('search','')
    if search_query:
        books= Books.objects.filter(Q(title__icontains = search_query)| Q(description__icontains= search_query))
    else:
        books= Books.objects.all().order_by('-publish')
    category = Category.objects.all()[0:5]
    paginator = Paginator(books,1)
    page = request.GET.get('page')
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)




    return render(request,'books_app/books_list.html',{'books':books,'categories':category})

def book_detail(request,slug):


    book= get_object_or_404(Books,slug = slug) 
    categories = Category.objects.all()[0:5]

    comments = book.comments.filter(active = True)
    if request.method == "POST":
        form  = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit = False)
            new_comment.book= book 
            new_comment.save()



            

    form = CommentForm()


    return render(request,'books_app/book_detail.html',{'book':book,'comments':comments,'form':form,'categories':categories})




def download_book(request,slug):
    book = Books.objects.get(slug=slug)
    return redirect(book.books_file.url)


def category_book(request,slug):

    category = Category.objects.get(slug = slug)
    books = Books.objects.filter(category = category)
    categories = Category.objects.all()
    paginator = Paginator(books,1)
    page = request.GET.get('page')
    

    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)




    return render(request,'books_app/books_list.html',{"books":books,'categories':categories,'category':category})








@login_required
@require_POST
def books_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    print(post_id)
    print(action)
    if post_id and action:
        try:
            book= Books.objects.get(id=post_id)
            if action == 'like':
                book.users_like.add(request.user)
            else:
                book.users_like.remove(request.user)

            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ok'})

my_blog/books_app/templates/books_app/book_detail.html
{% extends 'blog/base.html'%}	
{% block title%}{{book.title}} {% endblock%}

{% block meta_description%}{{book.meta_description}}{% endblock%}
{% block meta_keyword%}{{book.meta_keywords}}{% endblock %}

{% block content %}
		<div class="row">
			<div class="col-lg-8 main-content detail_content">
            <div class='container-fluid'>
            
            				<div class="card  mb-3">
                    <img class="card-img-top" src="{{book.books_image.url}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
                <p class="card-text mb-0"><small class="text-muted">Добавлено {{book.publish}}</small></p>
                <p class='card-text mb-3'><small class='text-muted'>Категория {{book.category}}</small></p>
                {{book.description|safe}}
                {{book.pk}}
                    </br>
                    <a class='mt-3 btn btn-primary' href='{% url 'books_app:download_book' book.slug%}'>Скачать книгу</a>
        {% with total_likes=book.users_like.count books_like=book.users_like.all %}
            <div class="card-body">
<div>
<span class="count" style='font-size:16px;'>
<span style='font-size:16px;' class="total text-uppercase ml-3 mt-2">{{ total_likes }}  </span>
like{{total_likes|pluralize}}
</span>
<a href="#" data-id="{{ book.id }}" data-action="{% if request.user in books_like%}un{% endif %}like"  class="like button btn btn-{% if request.user in books_like%}outline-{% endif %}success ml-2">
{% if request.user not in books_like%}
Like
{% else %}
Unlike
{% endif %}
</a>
</div>
</div>
            


            {% endwith %}
            </div>
          </div>
         {% with comments.count as total_comments %}
          <p class ='ml-3' style='font-size: 19px;'>Комментариев ({{total_comments}})</p>
          {% endwith %}
          {% for comment in comments %}
          
          <div class="card mb-3">
  
            <div class="card-body">
                <h5 class="card-title">{{comment.name}}</h5>
                <p class="card-text">{{comment.body}}</p>
                <p class="card-text"><small class="text-muted">{{comment.date}}</small></p>
    
            </div>
          </div>



          {% endfor %}


    {% if request.user.is_authenticated%}
          <form class='' action = '' method = 'post'>
              {% csrf_token %}
            <p class='ml-3' style='font-size: 19px;'>Добавить комментарий</p>
  <div class="row mb-2">
    <div class="col">
        {{form.name}}
    </div>
    <div class="col">
        {{form.email}}
    </div>
  </div>
  {{form.body}}
  <input type='submit' class='btn btn-primary mb-4' value= 'Отправить'>
  
</form>
{% else%}

          <p class ='ml-3 mt-3 mb-3' style='font-size: 19px;'>Чтобы оставить комментарий авторизуйтесь</p>
{%endif%}
            
            </div>


			</div>
			<div class="col-lg-4 mb-3 main-sidebar">
				<div class="list-group sticky-top mt-3">
					<h1 class = 'sidebar-category pl-3'>Категории</h1>
                    {% for category in categories %}

                    <a href="{{category.get_absolute_url}}" class="list-group-item list-group-item-action">{{category.title}}</a>
                    {% endfor %}

</div>
			</div>
		</div>


		
		
	</div>



    {% endblock%}	
   {% block domready %}

    $('a.like').click(function(e){
        e.preventDefault();
        $.post(
        '{% url 'books_app:like'%}',
        {id:$(this).data('id'),action:$(this).data('action')},
        function(data){
        console.log(data)
        if(data['status']=='ok'){
        var previous_action = $('a.like').data('action');
        $('a.like').data('action',previous_action =='like' ? 'unlike':'like');
        $('a.like').text(previous_action =='like' ? 'Unlike':'Like');
        var previous_likes = parseInt($('span.count .total').text());
        $('span.count .total').text(

        previous_action == 'like'?previous_likes+1:previous_likes-1);
        }
        }
        )


    })





{% endblock %}

my_blog/books_app/templates/books_app/books_list.html
{% extends 'blog/base.html'%}
{% block title%}{% if category%}Книги по {{category}}{% else%}Полезные книги{% endif%}{% endblock%}

{% block meta_description%}Книги, которые помогут начинающим программистам разобраться, как устроено програмимрование, web и другое{% endblock%}

{% block meta_keyword%}html, css, javascript, python, php, ajax, django, веб сервисы{% endblock %}





{% block content %}
<div class="row">
			<div class="col-lg-8 main-content">
            <div class='container-fluid'>
            				<ul>
                    {% if books %}
                    {% for book in books%}
                <li class='main-item mb-3 '>
						<div class="card mb-3">
                         <div class="row">
                           <div class="col-md-4">
                               <img src="{{book.books_image.url}}" style='height: 100%' class="card-img" alt="...">
                           </div>
                           <div class="col-md-8">
                             <div class="card-body">
                                 <a href="{{book.get_absolute_url}}" class='text-dark item-url'><h5 class="card-title mb-0">{{book.title}}</h5></a>
                                 <p class="card-text">{{book.description|truncatechars:60}}</p>
                               <div class="row">
                               	<div class="col-lg-6">
                                    
                                    <a class='btn btn-primary' href="{{book.get_absolute_url}}" style='text-decoration: none;color:#fff;'>Читать</a>
                               	</div>
                               	<div class="col-lg-6">
                                    <p class="card-text"><small class="text-muted">Создано {{book.publish}}</small></p>
                               	</div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
					</li>

                    {%endfor%}
                </ul>

        {% include 'blog/pagination.html' with page=books%}
                {% else%} 
                <h3 class='card-text'>Постов еще нет</h3>

                {% endif %}


            
            
            </div>


			</div>


			<div class="col-lg-4  mb-3 main-sidebar">
            <div class='container'>
                        
                    <nav class="navbar text-center p-0 mb-3">
                    <form class="form-inline" action='{% url 'books_app:list_book'%}'>
                        <div class='row'>
             <div class='col-sm-8 col-8'>
                        
                        
                  <input class="form-control  w-100" type="search" placeholder="Поиск" aria-label="Поиск" name='search'>
                        
                        </div>  

                        <div class='col-sm-4 col-4'>
                        
                        
                        
                  <button class="btn btn-outline-primary ml-2" type="submit">Поиск</button>
                        </div>
            
            
            
            
            
            </div> 
                </form>
              </nav>

                    
                    
                    </div>







				<div class="list-group sticky-top mt-3">

					<h1 class = 'sidebar-category pl-3'>Категории</h1>
                    {% for category in categories %}

                    <a href="{{category.get_absolute_url}}" class="list-group-item list-group-item-action">{{category.title}}</a>
                    {% endfor %}
                </div>
			</div>
		</div>

    
        {% endblock%}
{% block script %}
<script type='text/javascript'>
    function ajaxPagination(){
        $('ul.pagination a.page-link').each((index,el)=>{
            $(el).click((e)=>{
                e.preventDefault()
                let page_url = $(el).attr('href')

                var dfd = $.ajax({
                    url:page_url,
                    type:"GET",
                    async:true,
                    success:(data)=>{
                        $('.main-content').empty()
                    
                        $('.main-content').append($(data).find('.main-content').html())
                        ajaxPagination()
                    }
                })
            })
        })
    }


$(document).ready(function(){
    ajaxPagination()
})

</script>
{% endblock%}