my_blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.list,name='list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name = 'post_detail'),
    path('category/<slug:slug>/',views.post_category,name = 'category_list'),
    path('like/',views.post_like,name='like'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap
from services.sitemaps import ServiceSiteMap 
from questions.sitemaps import QuestionsSiteMap
from books_app.sitemaps import BooksSiteMap

sitemaps = {
        'posts':ArticleSitemap,
        'services':ServiceSiteMap,
        'questions':QuestionsSiteMap,
        'books':BooksSiteMap,
        }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}),
    path('services/',include('services.urls',namespace = 'service')),
    path('questions/',include('questions.urls',namespace='questions')),
    path('books/',include('books_app.urls',namespace='books_app')),
    path('auth/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('social-auth/',include('social_django.urls',namespace='social'))

    
    
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/questions/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'questions'

urlpatterns = [
    path('',views.show_questions,name='all_questions'),
    path('<slug:slug>',views.questions_detail, name='question_details'),
    path('tag/<slug:slug>',views.show_tag_questions,name ='tag_questions'),
    path('create_questions/',views.create_questions,name='create_questions'),
]

my_blog/questions/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
from pytils.translit import slugify
# Create your models here.

class QuestionsModel(models.Model):
    title = models.CharField(max_length = 250)
    name = models.CharField(max_length = 100,default='None',blank=True)
    email = models.EmailField()
    question = models.TextField(verbose_name = 'Вопрос')
    publish = models.DateTimeField(auto_now_add = True)
    answer = models.TextField(blank = True)
    slug = models.SlugField(unique = True)
    question_image = models.ImageField(upload_to='images/',blank = True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='questions')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'
        ordering = ('-publish',)

    tags = TaggableManager(verbose_name='Ключевые слова')
    
    def get_absolute_url(self):
        return reverse('questions:question_details',args = [self.slug])
    def save(self,  *args, **kwargs):
        self.slug = slugify(self.title)
        print(self.slug)
        return super(QuestionsModel, self).save(*args, **kwargs)



class Comment(models.Model):
    name = models.CharField(max_length = 50)
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add = True)
    body = models.TextField()
    post = models.ForeignKey(QuestionsModel,on_delete = models.CASCADE,related_name = 'comments')
    active = models.BooleanField(default = True)

    class Meta:
        verbose_name = 'Комментарий к ответу'
        verbose_name_plural = 'Комментарии к ответу'

    def __str__(self):
        return self.name

my_blog/questions/forms.py
from django.forms import ModelForm,TextInput,EmailInput,Textarea,FileInput
from .models import Comment,QuestionsModel

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','body']
        widgets = {'name':TextInput(attrs = {'class':'form-control','placeholder':'Имя'}),
                'email':EmailInput(attrs = {'class':'form-control','placeholder':'Email'}),
                'body':Textarea(attrs = {'class':'form-control mb-2','id':'exampleFormControlTextarea1','rows':'3','placeholder':'Текст комментария'})}


class QuestionForm(ModelForm):
    class Meta:
        model = QuestionsModel
        fields = ['title','name','email','tags','question','question_image']
        widgets = {'title':TextInput(attrs={'class':'form-control mb-2 w-100','placeholder':'Заголовок'}),
                   'name':TextInput(attrs={'class':'form-control mb-2 w-100','placeholder':'Имя'}),
                   'email':EmailInput(attrs ={'class':'form-control mb-2 w-100','placeholder':'Email'}),
                   'tags':TextInput(attrs = {'class':'form-control mb-2 w-100','placeholder':'Ключевые слова (пример: html, css, js)'}),
                   'question':Textarea(attrs = {'class':'form-control mb-2 w-100','id':'exampleFormControlTextarea1','placeholder':'Текст вопроса'}),
                   'question_image':FileInput(attrs = {'class':'form-control-file mb-2 '})}
    

my_blog/questions/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import QuestionsModel,Comment
from services.models import ServiceModel
from .forms import CommentForm,QuestionForm
from taggit.models import Tag
from django.db.models import Q

# Create your views here.


def show_questions(request):
    all_questions = QuestionsModel.objects.all()
    tags = Tag.objects.all()[0:5]
    search_query = request.GET.get('search','')
    if search_query:
        all_questions= QuestionsModel.objects.filter(Q(title__icontains = search_query)| Q(question__icontains = search_query) | Q(tags__name__in=[search_query]))
    else:
        all_questions= QuestionsModel.objects.all()
    
    paginator = Paginator(all_questions,10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)



    return render(request,'questions/all_questions.html',{'posts':posts,'tags':tags})



def questions_detail(request,slug):
    
     
     
    tags = Tag.objects.all()[0:5]

    question = get_object_or_404(QuestionsModel,slug = slug) 
    comments = question.comments.filter(active = True)
    if request.method == "POST":
        form  = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit = False)
            new_comment.post = question 
            new_comment.save()



            

    form = CommentForm()


    return render(request,'questions/question_detail.html',{'question':question,'form':form,'comments':comments,'tags':tags})



def show_tag_questions(request,slug):
    all_questions = QuestionsModel.objects.all()
        
    tag = None
    if slug:
        tag = get_object_or_404(Tag,slug=slug)
        all_questions = all_questions.filter(tags__in=[tag])


    tags = Tag.objects.all()[0:5]

    paginator = Paginator(all_questions,10)
    page = request.GET.get('page')
    try:
        all_questions= paginator.page(page)
    except PageNotAnInteger:
        all_questions= paginator.page(1)
    except EmptyPage:
        all_questions= paginator.page(paginator.num_pages)



    return render(request,'questions/tag_questions.html',{'questions':all_questions,'tags':tags,'tag':tag})

@login_required
def create_questions(request):
    if request.method =='POST':
        form = QuestionForm(request.POST,request.FILES)
        if form.is_valid():
            new_question = form.save(commit = False)
            if QuestionsModel.objects.filter(title = new_question.title).exists():
                return render(request,'questions/create_question.html',{'form':form,'message':'Такой вопрос уже существует в базе'})
            user = request.user
            new_question.user = user
            new_question.save()
            for tag in form.cleaned_data['tags']:
                new_question.tags.add(tag)
            return redirect('questions:all_questions')



    form  = QuestionForm()
    return render(request,'questions/create_question.html',{'form':form})

my_blog/questions/templates/questions/all_questions.html
{% extends 'blog/base.html'%}
{% block title%}Все вопросы{% endblock%}

{% block meta_description%}Все интерисующие вас вопросы по программированию{% endblock%}

{% block meta_keyword%}вопросы, html, css, js, python, django{% endblock %}



{% block content %}
<div class="row">
			<div class="col-lg-8 main-content">

                <div class='container-fluid'>
                
                <ul>
                    {% if posts%}
                    {% for post in posts%}
                <li class='main-item mb-3'>
						<div class="card mb-3">
                         <div class="row">
                           <div class="col-md-12">
                             <div class="card-body">

                                 <a href="{{post.get_absolute_url}}" class='text-dark item-url'><h5 class="card-title mb-0">{{post.title}}</h5></a>
                                 <p class="card-text">{{post.question|truncatechars:100}}</p>
                               <div class="row">
                               	<div class="col-lg-6">
                                    
                                    <a class='btn btn-primary' href='{{post.get_absolute_url}}' style='text-decoration: none;color:#fff;'>Посмотреть ответ</a>
                               	</div>
                               	<div class="col-lg-6">
                                    <p class="card-text"><small class="text-muted">Создано {{post.publish}}</small></p>
                               	</div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
					</li>

                    {%endfor%}

        {% include 'blog/pagination.html' with page=posts%}
                     {% else %}
                     <h3 class='card-title'> Вопросов еще нет</h3>
                      {% endif %}


                </ul>


                
                
                </div>


                
                </div>


			<div class="col-lg-4  mb-3 main-sidebar">

        <a href='{% url 'questions:create_questions'%}' class='btn btn-primary mb-3 w-100'>Добавить вопрос</a>

<div class='container'>
                    
                    <nav class="navbar text-center p-0 mb-3">

                    <form class="form-inline" action='{% url 'questions:all_questions'%}'>
                        <div class='row'>
 <div class='col-sm-8 col-8'>
                        
                        
                  <input class="form-control  w-100" type="search" placeholder="Поиск" aria-label="Поиск" name='search'>
                        
                        </div>  

                        <div class='col-sm-4 col-4'>
                        
                        
                        
                  <button class="btn btn-outline-primary ml-2" type="submit">Поиск</button>
                        </div>
            
            
            
            
            
            </div> 
                </form>
              </nav>

                    
                    
                    </div>






								<div class="list-group sticky-top mt-3">

					<h1 class = 'sidebar-category pl-3'>Тэгги</h1>
                    {% for tag in tags %}

                    <a href="{% url 'questions:tag_questions' slug=tag.slug%}" class="list-group-item list-group-item-action">{{tag.name}}</a>
                    {% endfor %}
                </div>
			</div>
		</div>

    
        {% endblock%}
{% block script %}
<script type='text/javascript'>
    function ajaxPagination(){
        $('ul.pagination a.page-link').each((index,el)=>{
            $(el).click((e)=>{
                e.preventDefault()
                let page_url = $(el).attr('href')

                var dfd = $.ajax({
                    url:page_url,
                    type:"GET",
                    async:true,
                    success:(data)=>{
                        $('.main-content').empty()
                    
                        $('.main-content').append($(data).find('.main-content').html())
                        ajaxPagination()
                    }
                })
            })
        })
    }


$(document).ready(function(){
    ajaxPagination()
})

</script>
{% endblock%}

my_blog/questions/templates/questions/create_question.html
{% extends 'blog/base.html'%}
{% block title%}Задайте вопрос{% endblock%}
{% block meta_description%}Добавьте интересующий вас вопрос, чтобы получить на него ответ{% endblock%}




{% block content %}
<div class="row">
        <form class='w-100' enctype="multipart/form-data" action ='' method='post'>
            {% csrf_token%}
            {% if message %}
            <h5 class='card-text mb-3 text-danger'>{{message}}</h5>
            {% endif %}
            {{form.title}}
            {{form.email}}
            {{form.tags}}
            {{form.question}}
            <h6 class='card-text'>Загрузите изображения (не обязательно)</h6>{{form.question_image}}</br>

           <button type='submit' class='btn btn-primary w-100 mb-5'>Задать вопрос</button> 
        
        
        </form>




		</div>

    
        {% endblock%}

my_blog/questions/templates/questions/question_detail.html
{% extends 'blog/base.html'%}	
{% block title%}{{question.title}} {% endblock%}

{% block meta_description%}{{question.title}} {{question.question}}{% endblock%}

{% block meta_keyword%}{% for t in question.tags.all%}{{t.name}}, {%endfor%}{% endblock %}

{% block content %}
		<div class="row">
			<div class="col-lg-8 main-content detail_content">
				<div class='container-fluid'>
                <div class="card  mb-3">
            <div class="card-body">
                <h5 class="card-title">{{question.title}}</h5>
                <p class="card-text mb-0"><small class="text-muted">Автор {{question.user.username}}: Создано {{question.publish}}</small></p>
                <p class='card-text mb-3'><small class='text-muted'>Тэгги: {% for t in question.tags.all%}<a href='{% url 'questions:tag_questions' slug=t.slug%}' class='card-text text-muted'>{{t.name}}</a> {% endfor %}</small></p>
                <p class='card-text mb-3'>{{question.question}}</p>
                

                {% if question.question_image%}
                <img class="card-img-top" src="{{question.question_image.url}}" alt="Card image cap">

                {% endif %}

                {% if question.answer %}
                <h5 class='text-info mt-3'> Ответ </h5>
                <p class = 'card-text'>{{question.answer}}</p>

                {% endif%}
            </div>
          </div>
         {% with comments.count as total_comments %}
          <p class ='ml-3' style='font-size: 19px;'>Комментариев ({{total_comments}})</p>
          {% endwith %}
          {% for comment in comments %}
          
          <div class="card mb-3">
  
            <div class="card-body">
                <h5 class="card-title">{{comment.name}}</h5>
                <p class="card-text">{{comment.body}}</p>
                <p class="card-text"><small class="text-muted">{{comment.date}}</small></p>
    
            </div>
          </div>



          {% endfor %}


          <form class='' action = '' method = 'post'>
              {% csrf_token %}
            <p class='ml-3' style='font-size: 19px;'>Добавить комментарий</p>
  <div class="row mb-2">
    <div class="col">
        {{form.name}}
    </div>
    <div class="col">
        {{form.email}}
    </div>
  </div>
  {{form.body}}
  <input type='submit' class='btn btn-primary mb-4' value= 'Отправить'>
  
</form>

        



                
                </div>

			</div>
			<div class="col-lg-4 main-sidebar">
				<div class="list-group sticky-top mt-3">

                    <a href='{% url 'questions:create_questions'%}' class='btn btn-primary mb-3 w-100'>Добавить вопрос</a>
					<h1 class = 'sidebar-category pl-3'>Тэгги</h1>
                    {% for tag in tags %}

                    <a href="{% url 'questions:tag_questions' slug=tag.slug%}" class="list-group-item list-group-item-action">{{tag.name}}</a>
                    {% endfor %}


</div>
			</div>
		</div>


		
		
	</div>



    {% endblock%}	

my_blog/questions/templates/questions/tag_questions.html
{% extends 'blog/base.html'%}
{% block title%}Вопросы по {{tag}}{% endblock%}

{% block meta_keyword%}вопросы, html, css, js, python, django{% endblock %}




{% block content %}
<div class="row">
			<div class="col-lg-8 main-content">
            <div class='container-fluid'>
            
            				<ul>
                {% if questions%}
                    {% for question in questions %}
                <li class='main-item mb-3 pr-2'>
						<div class="card mb-3">
                         <div class="row">
                           <div class="col-md-12">
                             <div class="card-body">

                                 <a href="{{question.get_absolute_url}}" class='text-dark item-url'><h5 class="card-title mb-0">{{question.title}}</h5></a>
                                 <p class="card-text">{{question.question|truncatechars:100}}</p>
                               <div class="row">
                               	<div class="col-lg-6">
                                    
                                    <a class='btn btn-primary' href='{{question.get_absolute_url}}' style='text-decoration: none;color:#fff;'>Посмотреть ответ</a>
                               	</div>
                               	<div class="col-lg-6">
                                    <p class="card-text"><small class="text-muted">Создано {{question.publish}}</small></p>
                               	</div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
					</li>

                    {%endfor%}

        {% include 'blog/pagination.html' with page=questions%}
                     {% else %}
                     <h3 class='card-title'> Вопросов еще нет</h3>
                      {% endif %}


                </ul>


            
            
            </div>




			</div>


			<div class="col-lg-4  mb-3 main-sidebar">

                <a href='{% url 'questions:create_questions'%}' class='btn btn-primary mb-3 w-100'>Добавить вопрос</a>
                <div class='container-fluid'>
                        
                    <nav class="navbar text-center p-0 mb-3">
                        
                    <form class="form-inline" action='{% url 'questions:all_questions'%}'>
                        <div class='row'>
                 <div class='col-sm-8 col-8'>
                            
                        
                  <input class="form-control  w-100" type="search" placeholder="Поиск" aria-label="Поиск" name='search'>
                        
                        </div>  

                        <div class='col-sm-4 col-4'>
                        
                        
                        
                  <button class="btn btn-outline-primary ml-2" type="submit">Поиск</button>
                        </div>
            
            
            
            
            
            </div> 
                </form>
              </nav>

                    
                    
                    </div>







                <div class="list-group sticky-top mt-3">

					<h1 class = 'sidebar-category pl-3'>Тэгги</h1>
                    {% for tag in tags %}

                    <a href="{% url 'questions:tag_questions' slug=tag.slug%}" class="list-group-item list-group-item-action">{{tag.name}}</a>
                    {% endfor %}
                </div>
			</div>
		</div>

    
        {% endblock%}
{% block script %}
<script type='text/javascript'>
    function ajaxPagination(){
        $('ul.pagination a.page-link').each((index,el)=>{
            $(el).click((e)=>{
                e.preventDefault()
                let page_url = $(el).attr('href')

                var dfd = $.ajax({
                    url:page_url,
                    type:"GET",
                    async:true,
                    success:(data)=>{
                        $('.main-content').empty()
                    
                        $('.main-content').append($(data).find('.main-content').html())
                        ajaxPagination()
                    }
                })
            })
        })
    }


$(document).ready(function(){
    ajaxPagination()
})

</script>
{% endblock%}