my_blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.list,name='list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name = 'post_detail'),
    path('category/<slug:slug>/',views.post_category,name = 'category_list'),
    path('like/',views.post_like,name='like'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap
from services.sitemaps import ServiceSiteMap 
from questions.sitemaps import QuestionsSiteMap
from books_app.sitemaps import BooksSiteMap

sitemaps = {
        'posts':ArticleSitemap,
        'services':ServiceSiteMap,
        'questions':QuestionsSiteMap,
        'books':BooksSiteMap,
        }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}),
    path('services/',include('services.urls',namespace = 'service')),
    path('questions/',include('questions.urls',namespace='questions')),
    path('books/',include('books_app.urls',namespace='books_app')),
    path('auth/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('social-auth/',include('social_django.urls',namespace='social'))

    
    
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/services/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'service'

urlpatterns = [
    path('service/<slug:slug>/',views.services,name='services'),
    path("<slug:slug>/<slug:ser>/",views.service_detail,name='service_post'),

    path('like/',views.service_like,name='service_like'),
]

my_blog/services/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

class ServiceModel(models.Model):
    title = models.CharField(max_length = 50)
    slug = models.SlugField(blank = True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-title',)
        verbose_name = 'Сервис'
        verbose_name_plural = 'Сервисы'

    def get_absolute_url(self):
        return reverse('service:services',  args = [self.slug])


class ServicePost(models.Model):
    STATUS_CHOICE = (
            ('draft',"Draft"),
            ('publish',"Publish")
            )
    author = models.ForeignKey(User,on_delete = models.CASCADE,related_name = 'service_post')

    service= models.ForeignKey(ServiceModel,on_delete = models.CASCADE)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length = 250,unique = True)
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    create = models.DateTimeField(auto_now_add = True)
    update = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 10,choices = STATUS_CHOICE,default = 'draft')
    image = models.ImageField()
    meta_description = models.CharField(max_length = 255,verbose_name='Мета дескриптион')
    meta_keywords = models.CharField(max_length = 255,verbose_name = 'Мета ключевые слова')

    service_like= models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='service_like',blank=True)

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Статья сервиса'
        verbose_name_plural = 'Статьи сервиса'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('service:service_post',  args = [self.service.slug,self.slug])


class Comment(models.Model):
    name = models.CharField(max_length = 50)
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add = True)
    body = models.TextField()
    post = models.ForeignKey(ServicePost,on_delete = models.CASCADE,related_name = 'comments')
    active = models.BooleanField(default = True)

    class Meta:
        ordering = ('-date',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.name

my_blog/services/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from .models import ServicePost,ServiceModel
from .forms import CommentForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


# Create your views here.

def services(request,slug):
    services = ServiceModel.objects.all()
    service= ServiceModel.objects.get(slug = slug)
    articles = ServicePost.objects.all().filter(service=service,status = 'publish')
    draft_articles = ServicePost.objects.all().filter(status ='draft' )
    paginator = Paginator(articles,1)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    
    
    return render(request,'services/services_list.html',{'posts':posts,'all_service':services,'page':page,'draft_articles':draft_articles,'service':service})

def service_detail(request,slug,ser):
    service = ServiceModel.objects.get(slug=slug)
    
    services = ServiceModel.objects.all()
    post = get_object_or_404(ServicePost,service = service ,slug = ser) 
    

    comments = post.comments.filter(active = True)

    if request.method == "POST":
        form  = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit = False)
            new_comment.post = post
            new_comment.save()



            

    form = CommentForm()
    return render(request,'services/services_post.html',{'post':post,'comments':comments,'form':form,'all_service':services})


    
@login_required
@require_POST
def service_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = ServicePost.objects.get(id=post_id)
            if action == 'like':
                post.service_like.add(request.user)
            else:
                post.service_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ok'})

my_blog/services/templates/services/services_list.html
{% extends 'blog/base.html'%}
{% block title%}{{service}}{% endblock%}

{% block meta_description%}Полезные статьи на тему {{service}}{% endblock%}

{% block meta_keyword%} html, css, js, python, django, {% for s in services%}{{s.title}}, {% endfor %}{% endblock %}


{% block content %}
<div class="row">
			<div class="col-lg-8 main-content">


            <div class='container-fluid'>
            <ul>
                {% if user.is_authenticated%}
                    {% for post in draft_articles%}
                <li class='main-item mb-3 '>
						<div class="card mb-3">
                         <div class="row">
                           <div class="col-md-4">
                               <img src="{{post.image.url}}" style='height: 100%' class="card-img" alt="...">
                           </div>
                           <div class="col-md-8">
                             <div class="card-body">
                                 <a href="{{post.get_absolute_url}}" class='text-dark item-url'><h5 class="card-title mb-0">{{post.title}}</h5></a>
                                 <p class="card-text">{{post.body|truncatechars:60}}</p>
                               <div class="row">
                               	<div class="col-lg-6">
                                    
                                    <a class='btn btn-primary' href="{{post.get_absolute_url}}" style='text-decoration: none;color:#fff;'>Читать</a>
                               	</div>
                               	<div class="col-lg-6">
                                    <p class="card-text"><small class="text-muted">Создано {{post.publish}}</small></p>
                               	</div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
					</li>

                    {%endfor%}
                {% endif%}
                    {% if posts %}
                    {% for post in posts%}
                <li class='main-item mb-3 '>
						<div class="card mb-3">
                         <div class="row">
                           <div class="col-md-4">
                               <img src="{{post.image.url}}" style='height: 100%' class="card-img" alt="...">
                           </div>
                           <div class="col-md-8">
                             <div class="card-body">
                                 <a href="{{post.get_absolute_url}}" class='text-dark item-url'><h5 class="card-title mb-0">{{post.title}}</h5></a>
                                 <p class="card-text">{{post.body|truncatechars:60}}</p>
                               <div class="row">
                               	<div class="col-lg-6">
                                    
                                    <a class='btn btn-primary' href="{{post.get_absolute_url}}" style='text-decoration: none;color:#fff;'>Читать</a>
                               	</div>
                               	<div class="col-lg-6">
                                    <p class="card-text"><small class="text-muted">Создано {{post.publish}}</small></p>
                               	</div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
					</li>

                    {%endfor%}
                </ul>

        {% include 'blog/pagination.html' with page=posts%}
                {% else %}
                <h3>Постов еще нет</h3>

                {% endif %}


            
            
            
            </div>




            </div>


			<div class="col-lg-4  mb-3 main-sidebar">
				
				<div class="list-group sticky-top mt-3">

					<h1 class = 'sidebar-category pl-3'>Сервисы</h1>
                    {% for s in all_service%}

                    <a href="{{s.get_absolute_url}}" class="list-group-item list-group-item-action">{{s.title}}</a>
                    {% endfor %}
                </div>
			</div>
		</div>

    
        {% endblock%}






{% block script %}
<script type='text/javascript'>
    function ajaxPagination(){
        $('ul.pagination a.page-link').each((index,el)=>{
            $(el).click((e)=>{
                e.preventDefault()
                let page_url = $(el).attr('href')

                var dfd = $.ajax({
                    url:page_url,
                    type:"GET",
                    async:true,
                    success:(data)=>{
                        $('.main-content').empty()
                    
                        $('.main-content').append($(data).find('.main-content').html())
                        ajaxPagination()
                    }
                })
            })
        })
    }


$(document).ready(function(){
    ajaxPagination()
})

</script>
{% endblock%}

my_blog/services/templates/services/services_post.html
{% extends 'blog/base.html'%}	
{% block title%}{{post.title}} {% endblock%}

{% block meta_description%}{{post.meta_description}}{% endblock%}

{% block meta_keyword%} {{post.meta_keywords}}{% endblock %}
{% block content %}
		<div class="row">
			<div class="col-lg-8 main-content detail_content">
                <div class='container-fluid'>
                <div class="card mb-3">
                    <img class="card-img-top" src="{{post.image.url}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{post.title}}</h5>
                <p class="card-text mb-3"><small class="text-muted">Автор {{post.author}}: Создано {{post.create}}</small></p>
                {{post.body|safe}}
            </div>
{% with total_likes=post.service_like.count service_like=post.service_like.all %}
            <div class="card-body">
<div>
<span class="count" style='font-size:16px;'>
<span style='font-size:16px;' class="total text-uppercase ml-3 mt-2">{{ total_likes }}  </span>
like{{total_likes|pluralize}}
</span>
<a href="#" data-id="{{ post.id }}" data-action="{% if request.user in service_like%}un{% endif %}like"  class="like button btn btn-{% if request.user in service_like%}outline-{% endif %}success ml-2">
{% if request.user not in service_like%}
Like
{% else %}
Unlike
{% endif %}
</a>
</div>
</div>
            


            {% endwith %}
          </div>
         {% with comments.count as total_comments %}
          <p class ='ml-3' style='font-size: 19px;'>Комментариев ({{total_comments}})</p>
          {% endwith %}
          {% for comment in comments %}
          
          <div class="card  mb-3">
  
            <div class="card-body">
                <h5 class="card-title">{{comment.name}}</h5>
                <p class="card-text">{{comment.body}}</p>
                <p class="card-text"><small class="text-muted">{{comment.date}}</small></p>
    
            </div>
          </div>



          {% endfor %}


    {% if request.user.is_authenticated%}
          <form class='' action = '' method = 'post'>
              {% csrf_token %}
            <p class='ml-3' style='font-size: 19px;'>Добавить комментарий</p>
  <div class="row mb-2">
    <div class="col">
        {{form.name}}
    </div>
    <div class="col">
        {{form.email}}
    </div>
  </div>
  {{form.body}}
  <input type='submit' class='btn btn-primary mb-4' value= 'Отправить'>
  
</form>

     {% else%}

          <p class ='ml-3 mt-3 mb-3' style='font-size: 19px;'>Чтобы оставить комментарий авторизуйтесь</p>
          {% endif%}
               
                </div>	
            
            
            
            
            
            
            
            </div>
			<div class="col-lg-4 main-sidebar">
				<div class="list-group sticky-top mt-3">
					<h1 class = 'sidebar-category pl-3'>Сервисы</h1>
                    {% for s in all_service%}

                    <a href="{{s.get_absolute_url}}" class="list-group-item list-group-item-action">{{s.title}}</a>
                    {% endfor %}

</div>
			</div>
		</div>


		
		
	</div>



    {% endblock%}	
{% block domready %}

    $('a.like').click(function(e){
        e.preventDefault();
        $.post(
        '{% url 'service:service_like'%}',
        {id:$(this).data('id'),action:$(this).data('action')},
        function(data){
        console.log(data)
        if(data['status']=='ok'){
        var previous_action = $('a.like').data('action');
        $('a.like').data('action',previous_action =='like' ? 'unlike':'like');
        $('a.like').text(previous_action =='like' ? 'Unlike':'Like');
        var previous_likes = parseInt($('span.count .total').text());
        $('span.count .total').text(

        previous_action == 'like'?previous_likes+1:previous_likes-1);
        }
        }
        )


    })





{% endblock %}